---
basePath: /v1
host: fruits.shoppingmadeeasy.com


info:
  description: "Shopping Made Easy APIs."
  title: ShoppingMadeEasy
  version: "1.0.0"

paths:
  /offer:
    $ref: ./paths/offer.yml

schemes:
  - https

tags:
  - name: Offers
    description: "Offers related apis"

swagger: "2.0"
