---
basePath: /v1
host: fruits.shoppingmadeeasy.com


info:
  description: "Shopping Made Easy APIs."
  title: ShoppingMadeEasy
  version: "1.0.0"

paths:
  /shopping/company/orders:
    $ref: ./paths/create_orders.yml
  /shopping/company/retrieve/orders:
    $ref: ./paths/retrieve_orders.yml

schemes:
  - https

tags:
  - name: Order
    description: "Order related apis"

swagger: "2.0"
