
#####
POST {{gateway-service-host}}/shopping/company/orders
x-tracking-id: {{$uuid}}
Content-Type: application/json

{
  "userId": "userId3",
  "itemDetails": [
    {
      "itemId": "item1",
      "itemQuantity": "2"
    },
    {
      "itemId": "item2",
      "itemQuantity": "3"
    }
  ],
  "paymentDetails": {
    "paymentId": "1234567890",
    "cvv": "456"
  },
  "shippingAddressId": "34987654"
}

###

POST {{gateway-service-host}}/shopping/company/retrieve/orders
x-tracking-id: {{$uuid}}
Content-Type: application/json

{
  "userId": "userId3"
}

####
POST {{gateway-service-host}}/shopping/company/retrieve/orders
x-tracking-id: {{$uuid}}
Content-Type: application/json

{
  "userId": "userId3",
  "orderIds": [
    "3a70254a-8894-47a0-b395-06617e079fa5"
  ]
}
