
#####
##### Create Order endpoint
POST {{gateway-service-host}}/shopping/company/orders
x-tracking-id: {{$uuid}}
Content-Type: application/json

{
  "userId": "userId2",
  "itemDetails": [
    {
      "itemId": "item1",
      "itemQuantity": "2"
    },
    {
      "itemId": "item2",
      "itemQuantity": "3"
    }
  ],
  "paymentDetails": {
    "paymentId": "1234567890",
    "cvv": "456"
  },
  "shippingAddressId": "34987654"
}

###
##### Retreive ALL Orders for a user
POST {{gateway-service-host}}/shopping/company/retrieve/orders
x-tracking-id: {{$uuid}}
Content-Type: application/json

{
  "userId": "userId2"
}

####
##### Retreive particular Order for a user
POST {{gateway-service-host}}/shopping/company/retrieve/orders
x-tracking-id: {{$uuid}}
Content-Type: application/json

{
  "userId": "userId2",
  "orderIds": [
    "dcdb28bc-b478-4eee-904c-8a29c84e9b6a"
  ]
}
